name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish npm package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Setup Git identity (for npm version)
        run: |
          git config --local user.name "github-actions[bot]"      
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: npm version patch --no-git-tag-version

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
